
import java.sql.Date;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JFormattedTextField;
import javax.swing.JList;
import javax.swing.table.DefaultTableModel;






/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author acv
 */
public class FlightSchedulerGUI extends javax.swing.JFrame
{

    /**
     * Creates new form FlightSchedulerGUI
     */
    public FlightSchedulerGUI()
    {
        initComponents();
         bookingCustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel(Customer.getAllCustomers().toArray()));
         bookingFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel(Flight.getAllFlights().toArray()));
         bookingDayComboBox.setModel(new javax.swing.DefaultComboBoxModel(Day.getAllDay().toArray()));
         
         
         bookingFlightComboBox2.setModel(new javax.swing.DefaultComboBoxModel(Flight.getAllFlights().toArray()));
         bookingDayComboBox2.setModel(new javax.swing.DefaultComboBoxModel(Day.getAllDay().toArray()));
         
         
         bookingFlightComboBox3.setModel(new javax.swing.DefaultComboBoxModel(Flight.getAllFlights().toArray()));
         bookingDayComboBox3.setModel(new javax.swing.DefaultComboBoxModel(Day.getAllDay().toArray()));
         
         cancelCustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel(Customer.getAllCustomers().toArray()));
         cancelDateComboBox.setModel(new javax.swing.DefaultComboBoxModel(Day.getAllDay().toArray()));
         
         statusCustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel(Customer.getAllCustomers().toArray()));
         dropFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel(Flight.getAllFlights().toArray()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        bookingCustomerComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        bookingFlightComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        bookingDayComboBox = new javax.swing.JComboBox<>();
        bookingButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        bookingResults = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        customerNameTextfield = new javax.swing.JTextField();
        addCustomerButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        addCustomerResults = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        addFlight = new javax.swing.JButton();
        addFlightResult = new javax.swing.JTextField();
        addFlights = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        addSeats = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        bookingDayComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        bookingFlightComboBox2 = new javax.swing.JComboBox<>();
        StatusBooking = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        StatusBookers = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        bookingDayComboBox3 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        bookingFlightComboBox3 = new javax.swing.JComboBox<>();
        StatusWaitList = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        StatusWaitListbyDay = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        StatusByDate = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        DateCustomer = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        cancelCustomerComboBox = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cancelDateComboBox = new javax.swing.JComboBox<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        addCancelBox = new javax.swing.JTextArea();
        cancel = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        statusCustomerComboBox = new javax.swing.JComboBox<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        addFlightList = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        addDateList = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        statusBookingCustomer = new javax.swing.JButton();
        statusWaitListCustomer = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        dropFlightComboBox = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        addDropResult = new javax.swing.JTextArea();
        drop = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        addDate = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        addDateResult = new javax.swing.JTextArea();
        dateSpinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setText("Flight Scheduler");

        jLabel3.setText("Customer: ");

        bookingCustomerComboBox.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                bookingCustomerComboBoxComponentRemoved(evt);
            }
        });
        bookingCustomerComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                bookingCustomerComboBoxItemStateChanged(evt);
            }
        });
        bookingCustomerComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingCustomerComboBoxActionPerformed(evt);
            }
        });
        bookingCustomerComboBox.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                bookingCustomerComboBoxPropertyChange(evt);
            }
        });

        jLabel4.setText("Flight: ");

        jLabel5.setText("Day: ");

        bookingButton.setText("Book");
        bookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingButtonActionPerformed(evt);
            }
        });

        bookingResults.setEditable(false);
        bookingResults.setColumns(20);
        bookingResults.setRows(5);
        jScrollPane2.setViewportView(bookingResults);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bookingCustomerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bookingFlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bookingDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(bookingButton)))
                        .addGap(0, 437, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookingCustomerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(bookingFlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookingDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(53, 53, 53)
                .addComponent(bookingButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Booking", jPanel2);

        jLabel2.setText("Enter Customer Name: ");

        customerNameTextfield.setColumns(20);

        addCustomerButton.setText("Add Customer");
        addCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerButtonActionPerformed(evt);
            }
        });

        addCustomerResults.setEditable(false);
        addCustomerResults.setColumns(20);
        addCustomerResults.setRows(5);
        addCustomerResults.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(addCustomerResults);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addCustomerButton)
                            .addComponent(customerNameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(customerNameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addCustomerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Customer", jPanel1);

        jLabel6.setText("Flight:");

        addFlight.setText("add flight");
        addFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFlightActionPerformed(evt);
            }
        });

        addFlightResult.setEditable(false);
        addFlightResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFlightResultActionPerformed(evt);
            }
        });

        addFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFlightsActionPerformed(evt);
            }
        });

        jLabel7.setText("Seats: ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addSeats))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addFlights, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(330, 446, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addFlightResult)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addFlights, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(addSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(addFlight)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addFlightResult, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Flight ", jPanel3);

        jLabel8.setText("Date:");

        jLabel10.setText("Flight:");

        StatusBooking.setText("Status by date ");
        StatusBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusBookingActionPerformed(evt);
            }
        });

        jLabel11.setText("Bookers:");

        StatusBookers.setEditable(false);
        StatusBookers.setColumns(20);
        StatusBookers.setRows(5);
        jScrollPane6.setViewportView(StatusBookers);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 303, Short.MAX_VALUE)
                .addComponent(StatusBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bookingFlightComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bookingDayComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookingDayComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookingFlightComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(41, 41, 41)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StatusBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Status Booking List by Flight Day", jPanel5);

        jLabel12.setText("Date:");

        jLabel13.setText("Flight:");

        StatusWaitList.setText("Status by Flight Day");
        StatusWaitList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusWaitListActionPerformed(evt);
            }
        });

        jLabel14.setText("Waiters:");

        StatusWaitListbyDay.setText("Status by Day");
        StatusWaitListbyDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusWaitListbyDayActionPerformed(evt);
            }
        });

        StatusByDate.setEditable(false);
        StatusByDate.setColumns(20);
        StatusByDate.setRows(5);
        jScrollPane5.setViewportView(StatusByDate);

        jLabel15.setText("Flights:");

        DateCustomer.setColumns(20);
        DateCustomer.setRows(5);
        jScrollPane3.setViewportView(DateCustomer);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel15)
                        .addGap(240, 240, 240)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(192, 192, 192))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bookingDayComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bookingFlightComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(StatusWaitList, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(StatusWaitListbyDay)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(bookingDayComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookingFlightComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(40, 40, 40)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StatusWaitList)
                    .addComponent(StatusWaitListbyDay))
                .addGap(46, 46, 46)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14))
                .addGap(9, 9, 9)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Status Wait List by Day", jPanel6);

        cancelCustomerComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelCustomerComboBoxActionPerformed(evt);
            }
        });

        jLabel16.setText("Customer:");

        jLabel17.setText("Day:");

        addCancelBox.setEditable(false);
        addCancelBox.setColumns(20);
        addCancelBox.setRows(5);
        jScrollPane7.setViewportView(addCancelBox);

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cancelCustomerComboBox, 0, 112, Short.MAX_VALUE)
                                .addComponent(cancelDateComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelCustomerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cancelDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cancel Booking", jPanel7);

        jLabel18.setText("Customer: ");

        statusCustomerComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusCustomerComboBoxActionPerformed(evt);
            }
        });

        addFlightList.setEditable(false);
        addFlightList.setColumns(20);
        addFlightList.setRows(5);
        jScrollPane8.setViewportView(addFlightList);

        addDateList.setEditable(false);
        addDateList.setColumns(20);
        addDateList.setRows(5);
        jScrollPane9.setViewportView(addDateList);

        jLabel19.setText("Flight:");

        jLabel20.setText("Date:");

        statusBookingCustomer.setText("Status Booking Customer");
        statusBookingCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusBookingCustomerActionPerformed(evt);
            }
        });

        statusWaitListCustomer.setText("Status Wait List Customer");
        statusWaitListCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusWaitListCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane8)
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(statusCustomerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel19))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane9)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(statusWaitListCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(statusBookingCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(statusCustomerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusBookingCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusWaitListCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(jScrollPane9))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Status Customer", jPanel8);

        jLabel21.setText("Drop Flight:");

        addDropResult.setEditable(false);
        addDropResult.setColumns(20);
        addDropResult.setRows(5);
        jScrollPane10.setViewportView(addDropResult);

        drop.setText("Drop");
        drop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(dropFlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(drop, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dropFlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drop, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Drop Flight", jPanel9);

        jLabel9.setText("Date:");

        addDate.setText("add Date");
        addDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDateActionPerformed(evt);
            }
        });

        addDateResult.setEditable(false);
        addDateResult.setColumns(20);
        addDateResult.setRows(5);
        jScrollPane4.setViewportView(addDateResult);

        dateSpinner.setModel(new javax.swing.SpinnerDateModel());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(362, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addDate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(47, 47, 47)
                .addComponent(addDate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Day", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDateActionPerformed
        // TODO add your handling code here:
        /*java.util.Date utilStartDate = date.getDate();
        java.sql.Date sqlStartDate = new java.sql.Date(utilStartDate.getTime());
        Day.addNewDays(sqlStartDate);
        addDateResult.setText("Flight Day " + date.getDate() + " has been added.");*/
        SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");
        String spinnerValue = formater.format(dateSpinner.getValue());
        Date day = Date.valueOf(spinnerValue);        
        Day.addNewDays(day);
              
       addDateResult.setText("Flight Day " + dateSpinner.getValue() + " has been added.");
        bookingDayComboBox.setModel(new javax.swing.DefaultComboBoxModel(Day.getAllDay().toArray()));
        bookingDayComboBox2.setModel(new javax.swing.DefaultComboBoxModel(Day.getAllDay().toArray()));
        bookingDayComboBox3.setModel(new javax.swing.DefaultComboBoxModel(Day.getAllDay().toArray()));
        cancelDateComboBox.setModel(new javax.swing.DefaultComboBoxModel(Day.getAllDay().toArray()));
    }//GEN-LAST:event_addDateActionPerformed

    private void addFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFlightsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addFlightsActionPerformed

    private void addFlightResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFlightResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addFlightResultActionPerformed

    private void addFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFlightActionPerformed
        int seats;
        try{
            seats = Integer.parseInt(addSeats.getText());
        }
        catch(NumberFormatException e){
            addFlightResult.setText("Invalid Input! Please try again! ");
            return;
        }
        if(seats>2){
            addFlightResult.setText("Flight seats should no be more than 2 seats !");
            return;
        }
        if(seats<1){
            addFlightResult.setText("Flight seats should not be less than 1 seats !");
            return;
        }
        Flight.addNewFlight(addFlights.getText(), Integer.parseInt(addSeats.getText()));
        addFlightResult.setText("Flight name " + addFlights.getText() + " seats: "+ addSeats.getText()+"  has been added.");
        bookingFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel(Flight.getAllFlights().toArray()));
        bookingFlightComboBox2.setModel(new javax.swing.DefaultComboBoxModel(Flight.getAllFlights().toArray()));
        bookingFlightComboBox3.setModel(new javax.swing.DefaultComboBoxModel(Flight.getAllFlights().toArray()));
        dropFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel(Flight.getAllFlights().toArray()));
    }//GEN-LAST:event_addFlightActionPerformed

    private void bookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingButtonActionPerformed
        // TODO add your handling code here:
        String customer =(String) bookingCustomerComboBox.getSelectedItem();
        String flight =(String) bookingFlightComboBox.getSelectedItem();
        Date dates =(Date) bookingDayComboBox.getSelectedItem();
        Timestamp timestamp = new Timestamp(dates.getTime());

        java.util.Date utilStartDate = dates;
        java.sql.Date sqlStartDate = new java.sql.Date(utilStartDate.getTime());
        BookingQuaries.addBookings(customer, flight, sqlStartDate , timestamp);

        if( BookingQuaries.checking(flight, dates)==true){

            bookingResults.setText("Booking List: "+"  Customer: " + customer + "  Flight: "+ flight +"  Date: "+ dates +
                " has been added");

        }
        else{
            WaitList.addWaitList(customer , flight , sqlStartDate , timestamp);
            BookingQuaries.cancelBooking(customer, flight, sqlStartDate);

            bookingResults.setText("Sorry, this flight is not avalible. We will make it into Wait List");
        }
    }//GEN-LAST:event_bookingButtonActionPerformed

    private void bookingCustomerComboBoxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_bookingCustomerComboBoxPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingCustomerComboBoxPropertyChange

    private void bookingCustomerComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingCustomerComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingCustomerComboBoxActionPerformed

    private void bookingCustomerComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_bookingCustomerComboBoxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingCustomerComboBoxItemStateChanged

    private void bookingCustomerComboBoxComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_bookingCustomerComboBoxComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingCustomerComboBoxComponentRemoved

    private void addCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerButtonActionPerformed
        Customer.addNewCustomer(customerNameTextfield.getText());
        addCustomerResults.setText("Customer Name: " + customerNameTextfield.getText() + " has been added.");
        bookingCustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel(Customer.getAllCustomers().toArray()));
        cancelCustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel(Customer.getAllCustomers().toArray()));
        statusCustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel(Customer.getAllCustomers().toArray()));
    }//GEN-LAST:event_addCustomerButtonActionPerformed

    private void StatusBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusBookingActionPerformed
        // TODO add your handling code here:
        String flight =(String) bookingFlightComboBox2.getSelectedItem();
        Date dates =(Date) bookingDayComboBox2.getSelectedItem();
        java.util.Date utilStartDate = dates;
        java.sql.Date sqlStartDate = new java.sql.Date(utilStartDate.getTime());        
        StatusBookers.setText("");
        for(String b: BookingQuaries.statusbyDate(sqlStartDate, flight)){
           StatusBookers.append("Bookers:   "+b+"\n");
           }
    }//GEN-LAST:event_StatusBookingActionPerformed

    private void StatusWaitListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusWaitListActionPerformed
        // TODO add your handling code here:
        String flight =(String) bookingFlightComboBox3.getSelectedItem();
        Date dates =(Date) bookingDayComboBox3.getSelectedItem();
        java.util.Date utilStartDate = dates;
        java.sql.Date sqlStartDate = new java.sql.Date(utilStartDate.getTime());
        
        StatusByDate.setText("");
        DateCustomer.setText("");
         for(String b: WaitList.statusbyFlightDate(sqlStartDate, flight)){
           DateCustomer.append("Waiters:   "+b+"\n");
           }
    }//GEN-LAST:event_StatusWaitListActionPerformed

    private void StatusWaitListbyDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusWaitListbyDayActionPerformed
        // TODO add your handling code here:  
        Date dates =(Date) bookingDayComboBox3.getSelectedItem();
        java.util.Date utilStartDate = dates;
        java.sql.Date sqlStartDate = new java.sql.Date(utilStartDate.getTime());
        WaitList.statusByDate(sqlStartDate);
        StatusByDate.setText("");
        DateCustomer.setText("");
        for(String a: WaitList.dateFlight()){
               
          StatusByDate.append("Flight:   "+a +"\n");       
          
        }   
         for(String b: WaitList.dateCustomers()){
           DateCustomer.append("Waiters:   "+b+"\n");
           }
         
         
     
    }//GEN-LAST:event_StatusWaitListbyDayActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        String customer =(String) cancelCustomerComboBox.getSelectedItem();
        Date dates =(Date) cancelDateComboBox.getSelectedItem();
        java.util.Date utilStartDate = dates;
        java.sql.Date sqlStartDate = new java.sql.Date(utilStartDate.getTime());
        
        Cancel.setBookingFlight(sqlStartDate,customer);    
       
       
        if(Cancel.checkBooking()==false){
        addCancelBox.setText("Sorry, the customer does not book flights");
            }
        else{
        
        Cancel.cancelBooking(sqlStartDate, customer);
        Cancel.setNextBooker(Cancel.getBookingFlight(), sqlStartDate);
        
        if(Cancel.checkWaiter() == true){
       
        Cancel.addBooker(Cancel.getNextBooker() , Cancel.getBookingFlight() , sqlStartDate, Cancel.getNextTimestamp());
        Cancel.cancelWaiter(sqlStartDate, Cancel.getBookingFlight(), Cancel.getNextBooker() );
           
        addCancelBox.setText("Booker:  "+ customer + "  is cancelled. Waiter:  "+ Cancel.getNextBooker() +"  is added into booking list");
        Cancel.setNextBooker(Cancel.getBookingFlight(), sqlStartDate);
       
        }
        else{
         addCancelBox.setText("Booker:  "+ customer + "  is cancelled.");
                }
        }
        
        
            
        
    }//GEN-LAST:event_cancelActionPerformed

    private void cancelCustomerComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelCustomerComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelCustomerComboBoxActionPerformed

    private void statusCustomerComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusCustomerComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusCustomerComboBoxActionPerformed

    private void statusBookingCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusBookingCustomerActionPerformed
        // TODO add your handling code here:
        String customer =(String) statusCustomerComboBox.getSelectedItem();
        BookingQuaries.setBookingList(customer);
        addFlightList.setText("");
        addDateList.setText("");
        
        for(String a: BookingQuaries.flightBookingList()){      
          addFlightList.append("Flight:   "+a +"\n");       
        }   
        for(Date b: BookingQuaries.dateBookingList()){
           addDateList.append("Date:   "+b+"\n");
           }
    }//GEN-LAST:event_statusBookingCustomerActionPerformed

    private void statusWaitListCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusWaitListCustomerActionPerformed
        // TODO add your handling code here:
        String customer =(String) statusCustomerComboBox.getSelectedItem();
        WaitList.setWaitList(customer);
        addFlightList.setText("");
        addDateList.setText("");
        
        for(String a: WaitList.getStatusFlights()){      
          addFlightList.append("Flight:   "+a +"\n");       
        }   
        for(Date b: WaitList.getStatusDates()){
           addDateList.append("Date:   "+b+"\n");
           }
    }//GEN-LAST:event_statusWaitListCustomerActionPerformed

    private void dropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropActionPerformed
        // TODO add your handling code here:
        String flight =(String) dropFlightComboBox.getSelectedItem();
        Drop.dropFlight(flight);
        bookingFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel(Flight.getAllFlights().toArray()));
        bookingFlightComboBox2.setModel(new javax.swing.DefaultComboBoxModel(Flight.getAllFlights().toArray()));
        bookingFlightComboBox3.setModel(new javax.swing.DefaultComboBoxModel(Flight.getAllFlights().toArray()));
        dropFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel(Flight.getAllFlights().toArray()));
        
        
        addDropResult.setText("");
        Drop.setCustomerDate(flight);
                  
            if(Drop.checkBookingCustomers()==false){
            addDropResult.append("There is no customer in this flight!");
            }
            else{     
            for(Date b: Day.getAllDay()){
                Drop.setCustomerDate(flight);
            for(String a: Flight.getAllFlights()){                
            if(Drop.checkFlightSeats(Drop.getDate(), a) == false){                          
            }
            else{ 
              if(Drop.checkBookingCustomers()==true){
                 while(Drop.checkCustomerFlight()==true){
                     
                Drop.addBookings(Drop.getCustomer(), Drop.getEmptyFlight(), Drop.getDate(), Drop.getTimestamp());
                addDropResult.append("Customer: "+Drop.getCustomer()+" is changed to the flight: "+ Drop.getEmptyFlight() +" from the flight: "+ flight +" in date: "+ Drop.getDate()+"\n");
                Drop.cancelBooking(Drop.getCustomer() , flight, Drop.getDate());              
                Drop.setCustomerDate(flight);  
                Drop.checkFlightSeats(Drop.getDate(), a);
                Drop.checkBookingCustomers();
                 }
              }
              else{}
               }          
                
                }
            if(Drop.checkBookingCustomers()==true){
                Drop.cancelBooking(Drop.getCustomer() , flight, b);      
                addDropResult.append("Customer: "+Drop.getCustomer()+" is cancelled from the flight: "+ flight +"\n");
            }else{
            }
            }
          }
         for(String a: Drop.getAllFlightWaiter(flight)){
          addDropResult.append("Waiters: "+ a +"  is cancelled from the flight: "+ flight +"\n");
         }         
         Drop.dropWaitListFlight(flight);
    }//GEN-LAST:event_dropActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FlightSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FlightSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FlightSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FlightSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new FlightSchedulerGUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea DateCustomer;
    private javax.swing.JTextArea StatusBookers;
    private javax.swing.JButton StatusBooking;
    private javax.swing.JTextArea StatusByDate;
    private javax.swing.JButton StatusWaitList;
    private javax.swing.JButton StatusWaitListbyDay;
    private javax.swing.JTextArea addCancelBox;
    private javax.swing.JButton addCustomerButton;
    private javax.swing.JTextArea addCustomerResults;
    private javax.swing.JButton addDate;
    private javax.swing.JTextArea addDateList;
    private javax.swing.JTextArea addDateResult;
    private javax.swing.JTextArea addDropResult;
    private javax.swing.JButton addFlight;
    private javax.swing.JTextArea addFlightList;
    private javax.swing.JTextField addFlightResult;
    private javax.swing.JTextField addFlights;
    private javax.swing.JTextField addSeats;
    private javax.swing.JButton bookingButton;
    private javax.swing.JComboBox<String> bookingCustomerComboBox;
    private javax.swing.JComboBox<String> bookingDayComboBox;
    private javax.swing.JComboBox<String> bookingDayComboBox2;
    private javax.swing.JComboBox<String> bookingDayComboBox3;
    private javax.swing.JComboBox<String> bookingFlightComboBox;
    private javax.swing.JComboBox<String> bookingFlightComboBox2;
    private javax.swing.JComboBox<String> bookingFlightComboBox3;
    private javax.swing.JTextArea bookingResults;
    private javax.swing.JButton cancel;
    private javax.swing.JComboBox<String> cancelCustomerComboBox;
    private javax.swing.JComboBox<String> cancelDateComboBox;
    private javax.swing.JTextField customerNameTextfield;
    private javax.swing.JSpinner dateSpinner;
    private javax.swing.JButton drop;
    private javax.swing.JComboBox<String> dropFlightComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton statusBookingCustomer;
    private javax.swing.JComboBox<String> statusCustomerComboBox;
    private javax.swing.JButton statusWaitListCustomer;
    // End of variables declaration//GEN-END:variables
}
